package slave

const(
	MAX_PACKET_SIZE = 2 << 24 - 1

	DEFAULT_POOL_SIZE = 3

	COM_PING = 0x0e
)
const(
	CLIENT_LONG_PASSWORD	= 0x0001
	CLIENT_FOUND_ROWS	= 0x0002	
	CLIENT_LONG_FLAG	= 0x0004	
	CLIENT_CONNECT_WITH_DB	= 0x0008
	CLIENT_NO_SCHEMA	= 0x0010	
	CLIENT_COMPRESS	= 0x0020
	CLIENT_ODBC	= 0x0040
	CLIENT_LOCAL_FILES	= 0x0080
	CLIENT_IGNORE_SPACE	= 0x0100
	CLIENT_PROTOCOL_41	= 0x0200
	CLIENT_INTERACTIVE	= 0x0400
	CLIENT_SSL	= 0x0800
	CLIENT_IGNORE_SIGPIPE	= 0x1000
	CLIENT_TRANSACTIONS	= 0x2000
	CLIENT_RESERVED	= 0x4000
	CLIENT_SECURE_CONNECTION	= 0x8000
	CLIENT_MULTI_STATEMENTS	= 0x00010000
	CLIENT_MULTI_RESULTS	= 0x00020000
	CLIENT_PLUGIN_AUTH	= 0x80000
)
const(
	COM_QUERY = 0x03
	COM_REGISTER_SLAVE = 0x15
	COM_BINLOG_DUMP = 0x12
	BINLOG_DUMP_NEVER_STOP = 0x00
)

const(
	// 事件类
	UNKNOWN_EVENT= 0
	START_EVENT_V3= 1
	QUERY_EVENT= 2
	STOP_EVENT= 3
	ROTATE_EVENT= 4
	INTVAR_EVENT= 5
	LOAD_EVENT= 6
	SLAVE_EVENT= 7
	CREATE_FILE_EVENT= 8
	APPEND_BLOCK_EVENT= 9
	EXEC_LOAD_EVENT= 10
	DELETE_FILE_EVENT= 11
	NEW_LOAD_EVENT= 12
	RAND_EVENT= 13
	USER_VAR_EVENT= 14
	FORMAT_DESCRIPTION_EVENT= 15
	XID_EVENT= 16
	BEGIN_LOAD_QUERY_EVENT= 17
	EXECUTE_LOAD_QUERY_EVENT= 18
	TABLE_MAP_EVENT = 19
	PRE_GA_WRITE_ROWS_EVENT = 20
	PRE_GA_UPDATE_ROWS_EVENT = 21
	PRE_GA_DELETE_ROWS_EVENT = 22
	WRITE_ROWS_EVENT_V1 = 23
	UPDATE_ROWS_EVENT_V1 = 24
	DELETE_ROWS_EVENT_V1 = 25
	INCIDENT_EVENT= 26
	HEARTBEAT_LOG_EVENT= 27
	IGNORABLE_LOG_EVENT= 28
	ROWS_QUERY_LOG_EVENT= 29
	WRITE_ROWS_EVENT = 30
	UPDATE_ROWS_EVENT = 31
	DELETE_ROWS_EVENT = 32
	GTID_LOG_EVENT= 33
	ANONYMOUS_GTID_LOG_EVENT= 34
	PREVIOUS_GTIDS_LOG_EVENT= 35
	TRANSACTION_CONTEXT_EVENT= 36
	VIEW_CHANGE_EVENT= 37
	XA_PREPARE_LOG_EVENT= 38
)

const (
	MYSQL_TYPE_JSON byte = iota + 0xf5
	MYSQL_TYPE_NEWDECIMAL
	MYSQL_TYPE_ENUM
	MYSQL_TYPE_SET
	MYSQL_TYPE_TINY_BLOB
	MYSQL_TYPE_MEDIUM_BLOB
	MYSQL_TYPE_LONG_BLOB
	MYSQL_TYPE_BLOB
	MYSQL_TYPE_VAR_STRING
	MYSQL_TYPE_STRING
	MYSQL_TYPE_GEOMETRY
)
const (
	MYSQL_TYPE_DECIMAL byte = iota
	MYSQL_TYPE_TINY
	MYSQL_TYPE_SHORT
	MYSQL_TYPE_LONG
	MYSQL_TYPE_FLOAT
	MYSQL_TYPE_DOUBLE
	MYSQL_TYPE_NULL
	MYSQL_TYPE_TIMESTAMP
	MYSQL_TYPE_LONGLONG
	MYSQL_TYPE_INT24
	MYSQL_TYPE_DATE
	MYSQL_TYPE_TIME
	MYSQL_TYPE_DATETIME
	MYSQL_TYPE_YEAR
	MYSQL_TYPE_NEWDATE
	MYSQL_TYPE_VARCHAR
	MYSQL_TYPE_BIT

	//mysql 5.6
	MYSQL_TYPE_TIMESTAMP2
	MYSQL_TYPE_DATETIME2
	MYSQL_TYPE_TIME2
)


const (
	BINLOG_CHECKSUM_ALG_OFF byte = 0 // Events are without checksum though its generator
	// is checksum-capable New Master (NM).
	BINLOG_CHECKSUM_ALG_CRC32 byte = 1 // CRC32 of zlib algorithm.
	//  BINLOG_CHECKSUM_ALG_ENUM_END,  // the cut line: valid alg range is [1, 0x7f].
	BINLOG_CHECKSUM_ALG_UNDEF byte = 255 // special value to tag undetermined yet checksum
	// or events from checksum-unaware servers
)
